apiVersion: v1
kind: ConfigMap
metadata:
  name: runtime-images
  namespace: redhat-ods-applications
data:
  custom.json: |-
    {
      "display_name": "Custom runtime w/ ultralytics and opencv",
      "metadata": {
        "tags": ["custom"],
        "display_name": "Custom runtime w/ ultralytics and opencv",
        "image_name": "quay.io/demo-ai-edge-crazy-train/activity-pipeline-runtime:v1",
        "pull_policy": "IfNotPresent"
      },
      "schema_name": "runtime-image"
    }