---
apiVersion: batch/v1
kind: Job
metadata:
  name: clone-repo
spec:
  backoffLimit: 4
  template:
    spec:
      serviceAccount: minio-manage
      serviceAccountName: minio-manage
      containers:
      - name: clone-repo
        image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args:
        - -ec
        - |-
          #!/usr/bin/env sh
          wait_for_exists () {
              # Arg1: selector
              # Arg2: namespace
              echo "IN"
              while true; do
                  pod_exists=$(oc -n $2 get po -oname -l $1 | wc -l)
                  if [ $pod_exists -gt 0 ]; then
                      echo "Selector $1 found in namespace $2"
                      break
                  fi
                  echo "Wait for selector $1 in namspace $2"
                  sleep 1
              done;
          }
          wait_for_exists "app=fine-tune" "traffic-sign-detection"
          oc -n traffic-sign-detection wait --timeout=-1s --for=condition=Ready=true po -l app=fine-tune
          pod=$(oc -n traffic-sign-detection get po -oname -l app=fine-tune -oname)
          oc exec -it ${pod} -- rm -rf activity-notebooks 2>/dev/null
          oc exec -it ${pod} -- git clone https://github.com/Demo-AI-Edge-Crazy-Train/activity-notebooks.git
      restartPolicy: Never