global:
  image:
    tag: latest
  pgConfig:
    host: label-studio-postgresql-hl
  extraEnvironmentVars:
    LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK: true
    LABEL_STUDIO_USERNAME: summit@redhat.com
    LABEL_STUDIO_PASSWORD: redhat
    LABEL_STUDIO_USER_TOKEN: redhat
  persistence:
    enabled: true
    type: volume
app:
  podLabels:
    app: label-studio
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  rbac:
    create: true

postgresql:
  enabled: true
  primary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
